(() => {
'use strict';
const $=id=>document.getElementById(id);
const els={
 video:$('video'),canvas:$('captureCanvas'),detector:$('detectorCanvas'),stage:$('cameraStage'),overlay:$('plateOverlay'),placeholder:$('placeholder'),
 start:$('startBtn'),stop:$('stopBtn'),targets:$('targetPlates'),targetCount:$('targetCount'),activeTargets:$('activeTargets'),tolerant:$('tolerantMode'),wake:$('wakeLockToggle'),interval:$('scanInterval'),roi:$('roiMode'),confidence:$('ocrConfidence'),
 status:$('statusPill'),primary:$('scanPrimaryStatus'),lastOcr:$('lastOcr'),closest:$('closestTarget'),similarity:$('similarity'),ocrTime:$('ocrTime'),scanCount:$('scanCount'),hitCount:$('hitCount'),
 banner:$('alertBanner'),bannerType:$('alertType'),bannerText:$('alertText'),log:$('hitLog'),clearLog:$('clearLogBtn'),testAlarm:$('testAlarmBtn'),error:$('errorBox'),
 setupView:$('setupView'),scanView:$('scanView'),logView:$('logView')
};
const APP_VERSION='8.0.0';
let stream=null,worker=null,running=false,busy=false,scanTimer=null,detectorTimer=null,wakeLock=null,audioCtx=null,scans=0,hits=0,lastHit=0,pendingReload=false,currentCandidate=null,boxToken=0;
const LOG_KEY='akls-v8-log';

const normalize=s=>(s||'').toUpperCase().replace(/Ä/g,'A').replace(/Ö/g,'O').replace(/Ü/g,'U').replace(/[^A-Z0-9]/g,'');
const pretty=s=>String(s||'').trim().toUpperCase().replace(/\s+/g,' ').replace(/\s*-\s*/g,'-');
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
function targets(){const seen=new Set();return (els.targets.value||'').split(/\n|,|;/).map(v=>v.trim()).filter(Boolean).map(raw=>({raw:pretty(raw),norm:normalize(raw)})).filter(x=>x.norm.length>=3&&!seen.has(x.norm)&&seen.add(x.norm));}
function levenshtein(a,b){const d=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=d[0];d[0]=i;for(let j=1;j<=b.length;j++){const t=d[j];d[j]=Math.min(d[j]+1,d[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=t;}}return d[b.length];}
function bestMatch(value){const v=normalize(value);let best=null;for(const t of targets()){const candidates=new Set([v]);if(v.length>=t.norm.length){for(let i=0;i<=v.length-t.norm.length;i++)candidates.add(v.slice(i,i+t.norm.length));}for(const c of candidates){const distance=levenshtein(c,t.norm);const sim=Math.round((1-distance/Math.max(c.length,t.norm.length,1))*100);if(!best||distance<best.distance||(distance===best.distance&&sim>best.similarity))best={target:t,value:c,distance,similarity:sim};}}return best;}
function plausiblePlate(s){const n=normalize(s);if(n.length<4||n.length>10)return false;if(!/[A-Z]/.test(n)||!/\d/.test(n))return false;return /^[A-Z]{1,5}\d{1,4}[EH]?$/.test(n)||/^[A-Z]{2,5}\d{1,4}$/.test(n);}
function displayPlate(n){const s=normalize(n);const m=s.match(/^([A-Z]{1,3})([A-Z]{1,2})(\d{1,4}[EH]?)$/);return m?`${m[1]}-${m[2]} ${m[3]}`:s;}
function setStatus(text,kind='idle'){els.status.textContent=text;els.status.className=`status-pill ${kind}`;els.primary.textContent=text;}
function showView(id){[els.setupView,els.scanView,els.logView].forEach(v=>{v.hidden=v.id!==id;v.classList.toggle('active-view',v.id===id)});document.querySelectorAll('.tab-button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='logView')renderLog();window.scrollTo({top:0,behavior:'auto'});}
function updateTargetCount(){const n=targets().length;els.targetCount.textContent=`${n} Zielkennzeichen`;els.activeTargets.textContent=String(n);localStorage.setItem('plateTargetsV8',els.targets.value);}
function error(msg=''){els.error.hidden=!msg;els.error.textContent=msg;}

function roiFractions(){switch(els.roi.value){case'wide':return{x:.02,y:.22,w:.96,h:.56};case'full':return{x:0,y:0,w:1,h:1};default:return{x:.05,y:.30,w:.90,h:.40};}}
function getVisibleSourceRect(){const vw=els.video.videoWidth,vh=els.video.videoHeight,sw=els.stage.clientWidth,sh=els.stage.clientHeight;if(!vw||!vh||!sw||!sh)return null;const sourceAR=vw/vh,stageAR=sw/sh;if(sourceAR>stageAR){const w=vh*stageAR;return{x:(vw-w)/2,y:0,w,h:vh,vw,vh}}const h=vw/stageAR;return{x:0,y:(vh-h)/2,w:vw,h,vw,vh};}
function sourceToStage(box){const v=getVisibleSourceRect();if(!v)return null;const sw=els.stage.clientWidth,sh=els.stage.clientHeight;return{left:(box.x-v.x)/v.w*sw,top:(box.y-v.y)/v.h*sh,width:box.w/v.w*sw,height:box.h/v.h*sh};}
function showBox(box,state,label,duration=0){if(!box)return;const p=sourceToStage(box);if(!p)return;const token=++boxToken;let div=els.overlay.querySelector('.plate-box');if(!div){div=document.createElement('div');div.className='plate-box';div.innerHTML='<span class="plate-label"></span>';els.overlay.appendChild(div);}div.className=`plate-box ${state}`;div.style.left=`${clamp(p.left,0,els.stage.clientWidth-6)}px`;div.style.top=`${clamp(p.top,0,els.stage.clientHeight-6)}px`;div.style.width=`${clamp(p.width,24,els.stage.clientWidth)}px`;div.style.height=`${clamp(p.height,12,els.stage.clientHeight)}px`;div.querySelector('.plate-label').textContent=label;div.hidden=false;if(duration)setTimeout(()=>{if(token===boxToken)div.hidden=true},duration);}
function clearBox(){boxToken++;els.overlay.innerHTML='';}

// Schneller Kandidatendetektor: sucht im ROI nach hellen, horizontalen, kantenreichen Rechtecken.
function detectPlateCandidate(){if(!running||els.video.readyState<2)return null;const v=getVisibleSourceRect();if(!v)return null;const r=roiFractions();const sx=v.x+v.w*r.x,sy=v.y+v.h*r.y,sw=v.w*r.w,sh=v.h*r.h;const c=els.detector,ctx=c.getContext('2d',{willReadFrequently:true});ctx.drawImage(els.video,sx,sy,sw,sh,0,0,c.width,c.height);const {data}=ctx.getImageData(0,0,c.width,c.height);const W=c.width,H=c.height;const gray=new Uint8Array(W*H);for(let i=0,p=0;i<data.length;i+=4,p++)gray[p]=(data[i]*30+data[i+1]*59+data[i+2]*11)/100;
 const integral=new Float64Array((W+1)*(H+1)),edgeInt=new Float64Array((W+1)*(H+1));for(let y=1;y<=H;y++){let row=0,erow=0;for(let x=1;x<=W;x++){const i=(y-1)*W+(x-1),g=gray[i];row+=g;const gx=x<W?Math.abs(g-gray[i+1]):0,gy=y<H?Math.abs(g-gray[i+W]):0;erow+=gx+gy;integral[y*(W+1)+x]=integral[(y-1)*(W+1)+x]+row;edgeInt[y*(W+1)+x]=edgeInt[(y-1)*(W+1)+x]+erow;}}
 const sum=(arr,x,y,w,h)=>arr[(y+h)*(W+1)+(x+w)]-arr[y*(W+1)+(x+w)]-arr[(y+h)*(W+1)+x]+arr[y*(W+1)+x];let best=null;const widths=[38,48,58,68,78],ratios=[2.7,3.2,3.8,4.5];for(const ww of widths){for(const ar of ratios){const hh=Math.max(10,Math.round(ww/ar));for(let y=2;y<=H-hh-2;y+=5){for(let x=2;x<=W-ww-2;x+=6){const area=ww*hh,mean=sum(integral,x,y,ww,hh)/area,edge=sum(edgeInt,x,y,ww,hh)/area;const centerBias=1-Math.abs((x+ww/2)-W/2)/(W/2);const score=edge*.62+Math.max(0,mean-70)*.18+centerBias*18;if(mean>65&&edge>24&&(!best||score>best.score))best={x,y,w:ww,h:hh,score};}}}}
 if(!best||best.score<34)return null;const padX=best.w*.10,padY=best.h*.35;return{x:sx+(best.x-padX)/W*sw,y:sy+(best.y-padY)/H*sh,w:(best.w+2*padX)/W*sw,h:(best.h+2*padY)/H*sh};}
function detectionLoop(){if(!running)return;const c=detectPlateCandidate();if(c){currentCandidate=c;showBox(c,'yellow','Kennzeichen erkannt');}detectorTimer=setTimeout(detectionLoop,180);}

function cropCandidate(){const v=getVisibleSourceRect();if(!v)return null;let b=currentCandidate;if(!b){const r=roiFractions();b={x:v.x+v.w*r.x,y:v.y+v.h*r.y,w:v.w*r.w,h:v.h*r.h};}const padX=b.w*.12,padY=b.h*.28;b={x:clamp(b.x-padX,0,els.video.videoWidth),y:clamp(b.y-padY,0,els.video.videoHeight),w:clamp(b.w+2*padX,1,els.video.videoWidth),h:clamp(b.h+2*padY,1,els.video.videoHeight)};const maxW=900,scale=Math.min(1,maxW/b.w);els.canvas.width=Math.max(1,Math.round(b.w*scale));els.canvas.height=Math.max(1,Math.round(b.h*scale));const ctx=els.canvas.getContext('2d');ctx.filter='contrast(1.35) grayscale(1)';ctx.drawImage(els.video,b.x,b.y,b.w,b.h,0,0,els.canvas.width,els.canvas.height);ctx.filter='none';return{canvas:els.canvas,box:b};}
function collectTexts(data){const out=[];if(Array.isArray(data.words))for(const w of data.words)out.push({text:w.text,confidence:w.confidence||data.confidence||0,bbox:w.bbox});const walkLines=blocks=>{for(const b of blocks||[])for(const p of b.paragraphs||[])for(const l of p.lines||[]){out.push({text:l.text,confidence:l.confidence||data.confidence||0,bbox:l.bbox});for(const w of l.words||[])out.push({text:w.text,confidence:w.confidence||data.confidence||0,bbox:w.bbox});}};walkLines(data.blocks);if(!out.length&&data.text)out.push({text:data.text,confidence:data.confidence||0,bbox:null});return out;}
function bestRead(data){const items=collectTexts(data);let best=null;for(const item of items){const n=normalize(item.text);if(!n)continue;let quality=(item.confidence||0)+(plausiblePlate(n)?30:0);if(/[A-Z]/.test(n)&&/\d/.test(n))quality+=15;if(!best||quality>best.quality)best={...item,n,quality};}return best;}

async function initWorker(){if(worker)return;if(!window.Tesseract)throw new Error('OCR konnte nicht geladen werden. Für den ersten Start ist Internet erforderlich.');setStatus('OCR lädt …','busy');worker=await Tesseract.createWorker('eng',1,{logger:m=>{if(m.status==='recognizing text'&&typeof m.progress==='number')setStatus(`OCR ${Math.round(m.progress*100)} %`,'busy')}});await worker.setParameters({tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',tessedit_pageseg_mode:'7',preserve_interword_spaces:'0'});}
async function scanOnce(){if(!running||busy)return;busy=true;const started=performance.now();try{const frame=cropCandidate();if(!frame)return;const result=await worker.recognize(frame.canvas,{}, {blocks:true,text:true});scans++;els.scanCount.textContent=String(scans);els.ocrTime.textContent=`${Math.round(performance.now()-started)} ms`;const read=bestRead(result.data);if(!read||!read.n||read.confidence<Number(els.confidence.value)){els.lastOcr.textContent='—';els.closest.textContent='—';els.similarity.textContent='—';return;}
 const plateBox=currentCandidate||frame.box;const label=displayPlate(read.n);showBox(plateBox,'green',label,1250);els.lastOcr.textContent=label;const bm=bestMatch(read.n);els.closest.textContent=bm?bm.target.raw:'—';els.similarity.textContent=bm?`${bm.similarity} %`:'—';addLog('read',label,'Kennzeichen korrekt gelesen');
 const allowed=els.tolerant.checked?1:0;if(bm&&bm.value&&bm.distance<=allowed){const now=Date.now();showBox(plateBox,'red',bm.target.raw,2800);setStatus('TREFFER','hit');showBanner(bm.target.raw);if(now-lastHit>4500){lastHit=now;hits++;els.hitCount.textContent=String(hits);addLog('hit',bm.target.raw,'Gesuchtes Kennzeichen erkannt');await alarm();}}
 }catch(e){console.warn(e);setStatus('Scan aktiv','active')}finally{busy=false;if(running)scanTimer=setTimeout(scanOnce,Number(els.interval.value));}}

async function ensureAudio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')await audioCtx.resume();}
async function alarm(){await ensureAudio();const now=audioCtx.currentTime;[0,.34,.68].forEach(o=>{const osc=audioCtx.createOscillator(),g=audioCtx.createGain();osc.type='square';osc.frequency.value=1050;g.gain.setValueAtTime(.0001,now+o);g.gain.exponentialRampToValueAtTime(.45,now+o+.015);g.gain.exponentialRampToValueAtTime(.0001,now+o+.22);osc.connect(g).connect(audioCtx.destination);osc.start(now+o);osc.stop(now+o+.25)});if(navigator.vibrate)navigator.vibrate([220,100,220,100,450]);}
function showBanner(plate){els.banner.hidden=false;els.bannerType.textContent='TREFFER!';els.bannerText.textContent=plate;clearTimeout(showBanner.t);showBanner.t=setTimeout(()=>{els.banner.hidden=true;if(running)setStatus('Scan aktiv','active')},3000);}

async function wake(){if(!els.wake.checked||!navigator.wakeLock)return;try{wakeLock=await navigator.wakeLock.request('screen')}catch(_){wakeLock=null}}
async function releaseWake(){try{await wakeLock?.release()}catch(_){}wakeLock=null;}
async function start(){error();if(!targets().length){error('Bitte mindestens ein Zielkennzeichen eintragen.');return}try{await ensureAudio();await initWorker();setStatus('Kamera startet …','busy');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});els.video.srcObject=stream;await els.video.play();running=true;els.placeholder.hidden=true;els.start.disabled=true;els.stop.disabled=false;showView('scanView');setStatus('Scan aktiv','active');await wake();detectionLoop();scanOnce();}catch(e){error(`Start fehlgeschlagen: ${e.message||e}`);setStatus('Fehler','hit');await stop(false);showView('setupView');}}
async function stop(back=true){running=false;clearTimeout(scanTimer);clearTimeout(detectorTimer);scanTimer=detectorTimer=null;busy=false;stream?.getTracks().forEach(t=>t.stop());stream=null;els.video.srcObject=null;els.placeholder.hidden=false;els.start.disabled=false;els.stop.disabled=true;clearBox();els.banner.hidden=true;await releaseWake();setStatus('Bereit','idle');if(back)showView('setupView');if(pendingReload)location.reload();}

function logs(){try{return JSON.parse(localStorage.getItem(LOG_KEY)||'[]')}catch(_){return[]}}
function addLog(kind,plate,note){const l=logs();l.unshift({kind,plate,note,time:Date.now()});localStorage.setItem(LOG_KEY,JSON.stringify(l.slice(0,100)));}
function renderLog(){const l=logs();if(!l.length){els.log.innerHTML='<div class="empty-log">Noch keine Ereignisse.</div>';return}els.log.innerHTML=l.map(x=>`<div class="log-item ${x.kind}"><div><div class="kind">${x.kind==='hit'?'TREFFER':x.kind==='read'?'GELESEN':'ERKANNT'}</div><strong>${escapeHtml(x.plate)}</strong><small>${escapeHtml(x.note)}</small></div><small>${new Date(x.time).toLocaleString('de-DE')}</small></div>`).join('');}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}

els.targets.addEventListener('input',updateTargetCount);els.start.addEventListener('click',start);els.stop.addEventListener('click',()=>stop(true));els.testAlarm.addEventListener('click',async()=>{const t=targets()[0];if(t){showView('scanView');showBanner(t.raw);setStatus('TREFFER','hit');await alarm();setTimeout(()=>{if(!running){setStatus('Bereit','idle');showView('setupView')}},2200)}});els.clearLog.addEventListener('click',()=>{localStorage.removeItem(LOG_KEY);renderLog()});document.querySelectorAll('.tab-button').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));document.addEventListener('visibilitychange',async()=>{if(document.visibilityState==='visible'&&running)await wake()});window.addEventListener('pagehide',()=>{if(running)stream?.getTracks().forEach(t=>t.stop())});

// V8: Kein dauerhafter "Neue Version verfügbar"-Banner. Updates werden automatisch aktiviert.
async function initServiceWorker(){if(!('serviceWorker'in navigator))return;let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloading)return;if(running){pendingReload=true;return}reloading=true;location.reload()});try{const reg=await navigator.serviceWorker.register('./sw.js?v=8',{updateViaCache:'none'});setTimeout(()=>reg.update().catch(()=>{}),1500);setInterval(()=>reg.update().catch(()=>{}),120000)}catch(e){console.warn('service worker',e)}}
const saved=localStorage.getItem('plateTargetsV8')||localStorage.getItem('plateTargets');if(saved)els.targets.value=saved;updateTargetCount();renderLog();initServiceWorker();
})();
